# Generated by Django 4.1.10 on 2024-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientEmail',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
