# Generated by Django 4.1.10 on 2024-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('contact', 'contact'), ('feedback', 'feedback')], max_length=50)),
            ],
        ),
    ]
