# Generated by Django 4.1.10 on 2024-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_appointment_patientlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientCity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientState',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='postalCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
