# Generated by Django 4.1.10 on 2024-06-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_appointment_patientcity_appointment_patientstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultStatus',
            field=models.CharField(choices=[('home', 'home'), ('hospital', 'hospital')], default='hospital', max_length=50),
        ),
    ]
