# Generated by Django 4.1.10 on 2024-06-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_appointment_consultstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
