# Generated by Django 4.1.10 on 2024-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientGender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientHeight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientWeight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
