# Generated by Django 4.1.10 on 2024-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_appointment_patientgender_appointment_patientheight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientAge',
            field=models.IntegerField(default=0),
        ),
    ]
