# Generated by Django 4.1.10 on 2024-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_appointment_patientapproved_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientApproved',
            field=models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('reject', 'reject')], default='pending', max_length=50),
        ),
    ]
