# Generated by Django 4.1.10 on 2024-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_appointment_patientapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
    ]
