# Generated by Django 4.1.10 on 2024-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_alter_bill_description_alter_bill_totalamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='description',
            new_name='billDescription',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='totalAmount',
        ),
        migrations.AddField(
            model_name='bill',
            name='totalBill',
            field=models.FloatField(default=0),
        ),
    ]
