# Generated by Django 4.1.10 on 2024-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_rename_description_bill_billdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
