# Generated by Django 4.1.10 on 2024-07-04 19:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_bill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
