# Generated by Django 4.1.10 on 2024-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0019_alter_bill_billdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billDescription',
            field=models.TextField(default=''),
        ),
    ]
