# Generated by Django 4.1.10 on 2024-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_alter_bill_billdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payBill',
            field=models.BooleanField(default=False),
        ),
    ]
