# Generated by Django 4.1.10 on 2024-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_bill_paybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='stripeId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
