# Generated by Django 4.1.10 on 2024-06-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choice',
        ),
    ]
