# Generated by Django 4.1.10 on 2024-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_profile_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choice',
            field=models.CharField(choices=[('doctor', 'doctor'), ('user', 'user')], default='user', max_length=30),
        ),
    ]
