# Generated by Django 4.1.10 on 2024-06-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_profile_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='choice',
            new_name='role',
        ),
    ]
